In [1]:
import numpy as np

# Create array
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:")
print(arr)

# Interchange rows and columns (Transpose)
transposed = arr.T

print("\nAfter Interchanging Rows and Columns:")
print(transposed)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After Interchanging Rows and Columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:", arr.shape)

# Move axis 0 to position 2
new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:", new_arr.shape)

print("\nNew Array:")
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)

New Array:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
import numpy as np

arr = np.array([[10, 20, np.nan],
                [30, np.nan, 50],
                [40, 60, 70]])

print("Original Array:")
print(arr)

# Column means ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column means
arr[inds] = np.take(col_mean, inds[1])

print("\nArray After Replacing NaN with Column Mean:")
print(arr)

Original Array:
[[10. 20. nan]
 [30. nan 50.]
 [40. 60. 70.]]

Array After Replacing NaN with Column Mean:
[[10. 20. 60.]
 [30. 40. 50.]
 [40. 60. 70.]]


In [4]:
import numpy as np

arr = np.array([10, -5, 20, -15, 30])

print("Original Array:")
print(arr)

arr = np.where(arr < 0, 0, arr)

print("\nAfter Replacing Negative Values with 0:")
print(arr)

Original Array:
[ 10  -5  20 -15  30]

After Replacing Negative Values with 0:
[10  0 20  0 30]


In [5]:
import numpy as np

arr = np.array([10, -5, 20, -15, 30])

arr[arr < 0] = 0

print(arr)

[10  0 20  0 30]
