In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

combined = np.vstack((arr1, arr2))

print("Combined Array:")
print(combined)

Combined Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print("Flattened Array:")
print(flat)

Flattened Array:
[1 2 3 4 5 6]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse = arr[::-1]

print("Reversed Array:")
print(reverse)

Reversed Array:
[50 40 30 20 10]


In [4]:
import numpy as np

arr = np.array([10, 25, 8, 45, 12])

print("Maximum Value =", np.max(arr))

Maximum Value = 45


In [5]:
import numpy as np

arr = np.array([10, 25, 8, 45, 12])

print("Minimum Value =", np.min(arr))

Minimum Value = 8


In [6]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

rows, cols = arr.shape

print("Rows =", rows)
print("Columns =", cols)

Rows = 2
Columns = 3


In [7]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("All Elements:")
for row in arr:
    for element in row:
        print(element, end=" ")

print("\n\nSpecific Element:")
print(arr[1, 2])

All Elements:
10 20 30 40 50 60 

Specific Element:
60


In [8]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

total = 0

for row in arr:
    for element in row:
        total += element

print("Sum =", total)

Sum = 21


In [9]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

Addition:
[12 24 35]

Subtraction:
[ 8 16 25]

Multiplication:
[ 20  80 150]

Division:
[5. 5. 6.]


In [10]:
import numpy as np

arr = np.array([[[1, 2],
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]]])

print("Using For Loop:")

for x in arr:
    for y in x:
        for z in y:
            print(z)

Using For Loop:
1
2
3
4
5
6
7
8


In [11]:
import numpy as np

arr = np.array([[[1, 2],
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]]])

print("Using nditer:")

for x in np.nditer(arr):
    print(x)

Using nditer:
1
2
3
4
5
6
7
8


In [12]:
import numpy as np
from scipy import stats

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Average Array
avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

# Combine Arrays
combined = np.concatenate((arr1, arr2))

print("\nCombined Array:")
print(combined)

# Mean
mean = np.mean(combined)
print("\nMean =", mean)

# Median
median = np.median(combined)
print("Median =", median)

# Mode
mode = stats.mode(combined, axis=None)

print("Mode =", mode.mode)

Average Array:
[[4. 5. 6.]
 [7. 8. 9.]]

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Mean = 6.5
Median = 6.5
Mode = 1
