In [5]:
import numpy as np

In [6]:
# Create NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:")
print(arr)

# Convert 1D array to 2D
arr2d = arr.reshape(2, 3)
print("\n1D to 2D Array:")
print(arr2d)

# Print Array Attributes
print("\nArray Attributes:")
print("Shape:", arr2d.shape)
print("Dimension:", arr2d.ndim)
print("Data Type:", arr2d.dtype)
print("Item Size:", arr2d.itemsize)

Original 1D Array:
[10 20 30 40 50 60]

1D to 2D Array:
[[10 20 30]
 [40 50 60]]

Array Attributes:
Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [7]:
# Create a 3×3 NumPy array of all 9
arr_9 = np.full((3, 3), 9)
print("\n3x3 Array of 9:")
print(arr_9)


3x3 Array of 9:
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [8]:
#  Create a 1D array of 10 evenly spaced values between 25 and 125
even_space = np.linspace(25, 125, 10)
print("\n10 Evenly Spaced Values:")
print(even_space)


10 Evenly Spaced Values:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [9]:
# Convert Python List into NumPy Array
py_list = [5, 10, 15, 20]
np_arr = np.array(py_list)
print("\nPython List to NumPy Array:")
print(np_arr)


Python List to NumPy Array:
[ 5 10 15 20]


In [10]:
# Reverse a 1D NumPy Array
reverse_arr = np_arr[::-1]
print("\nReversed Array:")
print(reverse_arr)


Reversed Array:
[20 15 10  5]


In [11]:
#  Create a 4×4×3 array and extract value
arr3d = np.arange(48).reshape(4, 4, 3)
print("\n4x4x3 Array:")
print(arr3d)

value = arr3d[1, 0, -1]
print("\nSecond Set, First Row, Last Column:")
print(value)


4x4x3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Second Set, First Row, Last Column:
14


In [12]:
#  Create a 4×4 array and extract Odd Rows and Even Columns
arr4x4 = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Array:")
print(arr4x4)

odd_rows_even_cols = arr4x4[::2, 1::2]
print("\nOdd Rows and Even Columns:")
print(odd_rows_even_cols)


4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [13]:
#  Slice first two rows and first two columns of second set
slice_arr = arr3d[1, :2, :2]
print("\nFirst Two Rows and First Two Columns of Second Set:")
print(slice_arr)


First Two Rows and First Two Columns of Second Set:
[[12 13]
 [15 16]]


In [14]:
#  Replace all odd numbers with -1 using for loop
arr_replace = np.array([[23, 56, 78, 93],
                        [71, 82, 13, 24]])

for i in range(arr_replace.shape[0]):
    for j in range(arr_replace.shape[1]):
        if arr_replace[i, j] % 2 != 0:
            arr_replace[i, j] = -1

print("\nReplace Odd Numbers with -1:")
print(arr_replace)


Replace Odd Numbers with -1:
[[-1 56 78 -1]
 [-1 82 -1 24]]


In [15]:
#  Get indices of non-zero elements
arr_nonzero = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr_nonzero)
print("\nIndices of Non-Zero Elements:")
print(indices)


Indices of Non-Zero Elements:
(array([0, 2, 4, 6]),)


In [16]:
#  Arithmetic Operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("\nAddition:")
print(a + b)

print("\nMultiplication:")
print(a * b)


Addition:
[11 22 33]

Multiplication:
[10 40 90]


In [17]:
#  Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("\nDot Product:")
print(dot_product)


Dot Product:
1875
